### ISSUE TITLE
continuity in html naming of interior component element

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-components#35]
IMO, it would benefit us if most "components" had a designated interior element. for example, `.card` would have a `.card__body`. It could also be called `.card__content`. I don't care what it's called.

This may seem like overkill, but sometimes designs necessitate a nested element like this for various reasons. One reason might be an "ON SALE" or "NEW" banner that only appears above one card in a series of cards. See attached image for a visual of this example. 
![cards](https://user-images.githubusercontent.com/2116946/110510474-36275680-80d1-11eb-97da-2fcf0756c2f9.png)
Another reason might be that you need to flex interior content but you don't want to hang this at the top-level.

A change like this would set us up for better spacing consistency in the future and we could avoid issues like "Why is the padding on cards different from tiles? Why doesn't the messaging content align with the content in the testimonial component below it?"

I could see this on many things: card, tile, messaging, testimonial, dropdown, accordion, layer, team, etc

**Comment by mbfitz** [comment]
@marcelmoreau - I totally agree! We should make this part of our BP updates and make sure everything has consistent markup. I'd also like to start a glossary or something where we list out names of our common components so we're all speaking the same language among our department and creative, ux, engineering.

**Comment by khamer** [comment]
I've updated [https://lexicon.imarc.host/](Lexicon), the glossary for Padstone and Boilerplate, to reflect our current conventions. `*__container` is what is used throughout Boilplerate for this wrapping element, as often this is also the same element that has the `.container` utility class or equivalent functionality.
