### ISSUE TITLE
accordion issues

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-components#81]
Original PR: https://github.com/imarc/boilerplate-components/pull/71

Still more to do here:

- the [accordion's readme](https://github.com/imarc/boilerplate-components/tree/next/resources/styles/molecules/accordion) has not been updated
  - props are not updated
  - transition name appears old/wrong
- the [Sass file's comments](https://github.com/imarc/boilerplate-components/blob/next/resources/styles/molecules/accordion/_index.scss#L1-L9) are old/not updated
- the icon should not shrink when more content is added (red outline in attached _accordion.png_)
- we need to left-align copy for the heading (yellow line)
- the heading does not align with the tab content (green line)
- there is extra spacing at the bottom of the tab content (blue line)
- we do not need [this line](https://github.com/imarc/boilerplate-components/blob/next/resources/styles/molecules/accordion/_index.scss#L20) as all buttons have this rule
- when closing an accordion on mobile (attached _accordion-clip.mp4_ file is iOS Safari), the content "stutters" near the end of the close before completely disappearing
- someone is going to note the content clipping on window re-size (attached _content-clip-window-resize.mp4_)
- we might consider increasing the [target tap area to at least 44x44 per WCAG](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) 

https://user-images.githubusercontent.com/2116946/178153492-d4d5644f-ac1a-47bd-8045-a20e324ef8df.mp4

![accordion](https://user-images.githubusercontent.com/2116946/178153493-e47e64e0-c9d8-402c-9a9a-f69fb3904ec6.png)

https://user-images.githubusercontent.com/2116946/178153494-0c0eedf5-55f2-4e81-a12a-b09c7654dbf2.mp4

**Comment by TristanMNorton** [comment]
https://github.com/imarc/boilerplate-components/commit/8b91650cdd2909d09452c3bc875884c6fc93ad02

This commit should have solved the stuttering, you might be looking at an older build.

**Comment by marcelmoreau** [comment]
I was looking on whatever is deployed to Netlify, which I think is set to be whatever has been committed to `next`. [`8b91650` is older than `dc5ba11`](https://github.com/imarc/boilerplate-components/commits/next) which is what [is deployed](https://app.netlify.com/sites/imarc-boilerplate/deploys)

**Comment by TristanMNorton** [comment]
Definitely not the latest as it doesn't have the additional wrapping element I added. I'll go through and address the rest of your feedback thought and get it finalized.

**Comment by TristanMNorton** [comment]
https://next--imarc-boilerplate.netlify.app/pattern-library/components/preview/accordion.html

This one is working. We might have been looking at the wrong one.

**Comment by TristanMNorton** [comment]
@marcelmoreau Just pushed updates based on the rest of your feedback. The only one I avoided is the extra space at the bottom. I assume whatever RTE/Redactor styles will normalize any spacing issues, and it's probably a separate conversation/PR if we think boilerplate-components should have some default RTE/Redactor mixin.

**Comment by marcelmoreau** [comment]
Nice looks good, I just made a couple edits:

- icon: use flex-shrink: 0 instead of giving it a min-width. this allows for edits to the svg's width/height attributes to work as intended. otherwise, making these smaller would not do anything
- icon: gave it a margin left so long content never butts up against it
- gave this a hover style as well
