### ISSUE TITLE
netlify info

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-components#82]
Cannot find any Netlify login information. I was QA'ing components on my phone browser that were seemingly committed to `next` and then `master`. Trying to see what branch is deploying but I can't find any info.

**Comment by khamer** [comment]
Netlify doesn't work like that.

**Comment by marcelmoreau** [comment]
the Netlify instance that controls this project has no login credentials at all? can we keep this issue open for purposes of fleshing out documentation for others about how it works?
